name: Scrape Realtor Leads (cron + manual)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # reduced to every 6 hours

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv

      - name: Run Realtor scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DEBUG: "true"
          # Add these to reduce request frequency
          MAX_LISTINGS_PER_SEARCH: "3"
          MAX_LISTINGS_TOTAL: "6"
        run: |
          PYTHONPATH=. python scripts/run_realtor.py
